### ISSUE TITLE
SNPs-Panopea

### ISSUE THREAD

**Issue by JVLF** [sr320/course-btea#15]
SNPs with adaptive value in Panopea globosa. The geoduck (Panopea globosa) is a sessile bivalve with a maximum shell length of 212 mm, and a live weight of 3.25 kg (including shell) (Goodwin & Pease, 1989) widely distributed in the northwestern coasts Mexico. The distribution of the species is influenced by ocean currents and the type of substrate that allows it to bury itself (Campbell et al., 1998). The first genetic analysis for P. globosa in the Upper Gulf of California (San Felipe and Puerto Peñasco) was performed with fragments of the ribosomal nuclear (rDNA); no genetic differentiation among populations were found (Rocha-Olivares et al., 2010). More recently, in an analysis conducted by Leyva-Valencia et al (2012) via geometric morphometry. of California (San Felipe and Puerto Peñasco) was performed with fragments of the ribosomal.

**Comment by sr320** [comment]
Wonderful! thanks for creating an issue :snowboarder:
