### ISSUE TITLE
I suggest to categories to vote

### ISSUE THREAD

**Issue by EugenioCarpizo** [sr320/course-btea#45]
Category 1. bioinformatics outreach
Category 2. Scientific research

**Comment by mdelrio1** [comment]
Agree!

**Comment by Patiiiitoo** [comment]
Agree too!

**Comment by sr320** [comment]
Done - two categories added to voting sheet
https://docs.google.com/spreadsheets/d/15SMbmvfKkFznhA1iESzomuTX8kWjDnCZbZqPTKoEh-A/edit#gid=0
