### ISSUE TITLE
Hi does Jupyter work on Internet Explorer? It doesn't seem to, which is odd.

### ISSUE THREAD

**Issue by carlauranga** [sr320/course-btea#49]
It's just that DAVID is working much better on Internet Explorer, however, when I tried to curl the data using Jupyter on Chrome, Jupyter did not allow it, this is the message I got:
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by sr320** [comment]
I could be wrong but I would not think there would be a problem on Internet Explorer. Does it work in a different browser?

**Comment by carlauranga** [comment]
I think it is just a matter of, and I think everyone knows this, the fact that Windows is not for computer programming!

**Comment by carlauranga** [comment]
Ok figured out a way to use Internet Explorer, much easier! One can export the data from DAVID directly into Excel.  Thought I would share :dancer:  Cheers!

**Comment by carlauranga** [comment]
Now if only we may connect to REVIGO life would be great!
