### ISSUE TITLE
Log in problem Git Hub desktop does not communicate with web browser

### ISSUE THREAD

**Issue by carlauranga** [sr320/course-btea#8]
My Windows 8.1 computer is not permitting the Git Hub desktop feature to communicate with the internet GitHub, therefore I am not able to log in and sync the two.

**Comment by sr320** [comment]
Here is a start on how to add files to repo using commandline
https://help.github.com/articles/adding-a-file-to-a-repository-from-the-command-line/

We can also troubleshoot more tomorrow :sunrise:
